### PR TITLE
build: Update pyproject.toml

### PR DESCRIPTION
**Pull request by ericbn**
Require flake8>=4.0.1. Avoid setting upper bound on flake8 requirement to support version 6.0.0 and future versions too. See https://iscinumpy.dev/post/bound-version-constraints

### CODE REVIEW

**Comment by pwoolvett** [comment]
py37 was not supported because it checked for ast posonlyargs (available since py38, see pep570).

I'm working on a patch to add back py37, although its EOL in 4 months...

(the ci passed because poetry ran on py39 instead of py37!!! Fix incoming as well)

**Comment by ericbn** [comment]
Got it! Just bumped the version to 0.2.0. Is that what was recommended by this error:

> The commits found are not elegible to be bumped

?

**Comment by ericbn** [comment]
I see sphinx-inline-tabs also requires Python>=3.8.

**Comment by pwoolvett** [comment]
1) do not manually bump the version, the ci will take care of it.
2) yes, and astpretty as well...

**Comment by pwoolvett** [comment]
Hey @ericbn thanks for your contribution.

Flake8 unpin (and others) now should be available from #4 , including py37 support explicitly dropped.


Superseded by #4

**Pull request closed without merging**
